# 0. Data Accuracy

For real numbers, float 64

* ex) 0.1453e-15
* $10^{-308}$ ~ $10^{308}$

For complex numbers, complex128

# 1. Vector and Matrix Representations

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]])

In [3]:
print(a)

[[ 1.   2.   5.3]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


$$\mathbf{a} = \begin{bmatrix} 
1 & 2 & 5.3 \\
-1 & -2 & -1.5 \\
4 & 5.5 & 6
\end{bmatrix}$$

In [4]:
b = np.array([4, 5, 6])

In [5]:
print(b)

[4 5 6]


$$\mathbf{b} = 
\begin{bmatrix}
4 \\
5 \\
6
\end{bmatrix}$$

# 2. Checking Sizes

$\mathbf{a}$ is a $3 \times 3$ matrix.

In [6]:
print(a.shape, "--> this is a tuple data type")

(3, 3) --> this is a tuple data type


$\mathbf{a}$ has 3 rows.

In [7]:
print(a.shape[0])

3


$\mathbf{a}$ has 3 columns.

In [8]:
print(a.shape[1])

3


$\mathbf{b}$ is a vector of size 3.

In [9]:
print(b.shape)

(3,)


In [10]:
print(b.shape[0])

3


In [11]:
print(b.shape[1]) # index error

IndexError: tuple index out of range

# 3. Vector and Matrix Representations (complex)

In [12]:
a = np.array([[1-2j, 3+1j,1], [1+2j, 2-1j, 7 + 0j]])

In [13]:
b = np.array([1+8j, -2j])

$
\mathbf{a} = 
\begin{bmatrix}
1 - 2j & 3 + 1j & 1 \\
1 + 2j & 2 - 1j & 7
\end{bmatrix},
\quad
\mathbf{b} = 
\begin{bmatrix}
1 + 8j \\
-2j
\end{bmatrix}$

# 4. Accessing Values

In [14]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]])

In [15]:
b = np.array([4, 5, 6])

$$\mathbf{a} = \begin{bmatrix} 
1 & 2 & 5.3 \\
-1 & -2 & -1.5 \\
4 & 5.5 & 6
\end{bmatrix} = 
\begin{bmatrix} 
\mathbf{a}[0, 0] & \mathbf{a}[0, 1] & \mathbf{a}[0, 2] \\
\mathbf{a}[1, 0] & \mathbf{a}[1, 1] & \mathbf{a}[1, 2] \\
\mathbf{a}[2, 0] & \mathbf{a}[2, 1] & \mathbf{a}[2, 2]
\end{bmatrix}$$

$$\mathbf{b} = 
\begin{bmatrix}
4 \\
5 \\
6
\end{bmatrix} = 
\begin{bmatrix}
\mathbf{b}[0] \\
\mathbf{b}[1] \\
\mathbf{b}[2]
\end{bmatrix}$$

example: $\mathbf{a}_{23}$

In [16]:
a[1, 2]

np.float64(-1.5)

In [17]:
a[1][2]

np.float64(-1.5)

example: $\mathbf{b}_3$

In [18]:
b[2]

np.int64(6)

This way, we can also alter the values.

In [19]:
print(a, "original")
a[1, 2] = 0
print(a, "new")

[[ 1.   2.   5.3]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]] original
[[ 1.   2.   5.3]
 [-1.  -2.   0. ]
 [ 4.   5.5  6. ]] new


However, when you try to change the value to a complex number, you will see an error message:

In [20]:
a[1, 2] = 3 + 7j

TypeError: float() argument must be a string or a real number, not 'complex'

When you first defined the matrix as below:
```python
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]])
```
actually, the data type argument was applied in the default setting as follows:

```python
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.float64)
```

This means all entries' data types are designated as $np.float64$.

In short, it is impossible to change the value to a complex number in this case.
To avoid this issue, from the beginning set the data type as $np.complex128$ as follows:

```python
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.complex128)
```

In [21]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.complex128)
print(a)
a[1, 2] = 3 + 7j
print(a)

[[ 1. +0.j  2. +0.j  5.3+0.j]
 [-1. +0.j -2. +0.j -1.5+0.j]
 [ 4. +0.j  5.5+0.j  6. +0.j]]
[[ 1. +0.j  2. +0.j  5.3+0.j]
 [-1. +0.j -2. +0.j  3. +7.j]
 [ 4. +0.j  5.5+0.j  6. +0.j]]


**Key takeaway: make sure to set the data type as $np.complex128$ to avoid such errors!**

The data type can also be coverted after it is initialized.

```python
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]])
a = a.astype(dtype = np.complex128)
```

An such error can be avoided.

In [22]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.float64)
a = a.astype(dtype = np.complex128)
a[1, 2] = 3 + 7j
print(a)

[[ 1. +0.j  2. +0.j  5.3+0.j]
 [-1. +0.j -2. +0.j  3. +7.j]
 [ 4. +0.j  5.5+0.j  6. +0.j]]


In some cases, when you are certain you are handling real matrices only, you can convert the complex data type matrix into real data type matrix.
In this case, you will see the warning message telling you the imaginary parts are discarded.

In [23]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.complex128)
a = a.astype(dtype = np.float64)

C:\Users\jhkan\AppData\Local\Temp\ipykernel_31868\1437958182.py:2: ComplexWarning: Casting complex values to real discards the imaginary part
  a = a.astype(dtype = np.float64)


$astype$ was a method for explicit data type conversion.
There are cases the data types are coverted implicitly.

In [24]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.float64)
c = np.array([[0, 1+5j, 3+2j], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.complex128)
a+c

array([[ 1. +0.j,  3. +5.j,  8.3+2.j],
       [-2. +0.j, -4. +0.j, -3. +0.j],
       [ 8. +0.j, 11. +0.j, 12. +0.j]])

In [25]:
a = np.array([[1, 2, 5.3], [-1, -2, -1.5], [4, 5.5, 6]], dtype = np.float64)
a = (1 + 3j) * a

However, it is advised against to rely on implicit data type conversion.

## Practice

$\begin{bmatrix} 
1 & 2 & 4 & 1 \\
2 & 1 & 3 & 1\\
5 & 2 & 1 & 4 \\
\end{bmatrix}$

1. represent the matrix using 2D array
2. check the dimesion of the matrix using shape method
3. change the (1, 3) and (3, 2) entries to 1 + 2i (complex number)
4. change the (1, 3) and (3, 2) entries to 0 

1. represent the matrix using 2D array

In [26]:
A = np.array([[1, 2, 4, 1], [2, 1, 3, 1], [5, 2, 1, 4]], dtype = np.float64) # real matrix

In [27]:
print(A)

[[1. 2. 4. 1.]
 [2. 1. 3. 1.]
 [5. 2. 1. 4.]]


2. check the dimesion of the matrix using shape method

In [28]:
print(A.shape) # 3 X 4 matrix

(3, 4)


3. change the (1, 3) and (3, 2) entries to 1 + 2i (complex number)

In [29]:
A = A.astype(dtype = np.complex128) # explict data type conversion

In [30]:
A[0, 2] = 1 + 2j
A[2, 1] = 1 + 2j

In [31]:
print(A)

[[1.+0.j 2.+0.j 1.+2.j 1.+0.j]
 [2.+0.j 1.+0.j 3.+0.j 1.+0.j]
 [5.+0.j 1.+2.j 1.+0.j 4.+0.j]]


4. change the (1, 3) and (3, 2) entries to 0 

In [32]:
A[0, 2] = 0
A[2, 1] = 0

In [33]:
print(A)

[[1.+0.j 2.+0.j 0.+0.j 1.+0.j]
 [2.+0.j 1.+0.j 3.+0.j 1.+0.j]
 [5.+0.j 0.+0.j 1.+0.j 4.+0.j]]
