In [1]:
import numpy as np
from scipy import linalg

# 1. Determinant

```python
det = linalg.det(A)
```

* applied algorithm: LU decompoition
* corresponding Lapack function
  1. zgetrf (z means complex128)
  2. dgetrf (d means float64)

$$
\text{Matrix 1: }
\begin{bmatrix}
1 & 5 & 0 \\
2 & 4 & -1 \\
0 & -2 & 0
\end{bmatrix}, \quad \text{determinant} = -2
$$

$$
\text{Matrix 2: }
\begin{bmatrix}
1 & -4 & 2 \\
-2 & 8 & -9 \\
-1 & 7 & 0
\end{bmatrix}, \quad \text{determinant} = 15
$$

In [2]:
A1 = np.array([
    [1, 5, 0],
    [2, 4, -1],
    [0, -2, 0]
], dtype = np.float64)

A2 = np.array([
    [1, -4, 2],
    [-2, 8, -9],
    [-1, 7, 0]
], dtype = np.float64)

In [3]:
# determinant

det1 = linalg.det(A1)
print("det1: ", det1)
print()
det2 = linalg.det(A2)
print("det2: ", det2)

det1:  -2.0

det2:  15.0


# 2. Inverse Matrix

```python
inv_A = linalg.inv(A)
```

* Note. refrain from computing an inverse if the purpose is to solve $A\mathbf{x} = \mathbf{b}$ (backward error problem)
* if $A$ is singular, error will occur
* even when $A$ is not singular, due to numerical methodical issues, it might display error as being singular
* applied algorithm: LU decompoition; solve $LUA^{-1} = 1, \quad \text{backsubstitution}$
* corresponding Lapack function
  1. getrf (LU decomposition)
  2. getri (when the matrix is triangular)

$$
A = 
\begin{bmatrix}
1 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 1
\end{bmatrix}, \quad
A^{-1} = 
\begin{bmatrix}
8 & -1 & -5 \\
-1 & 0 & 1 \\
-5 & 1 & 3
\end{bmatrix}
$$

In [4]:
A = np.array([
    [1, 2, 1],
    [2, 1, 3],
    [1, 3, 1]
], dtype = np.float64)

In [5]:
inv_A = linalg.inv(A)
print(inv_A)

[[ 8. -1. -5.]
 [-1.  0.  1.]
 [-5.  1.  3.]]


# 3. Solving $A\mathbf{x} = \mathbf{b}$

## 3.1 General Cases - general, symmetric, Hermitian, positive definte

```python
x = linalg.slove(A, b, assume_a = "gen")
```

* ```assume_a = "gen"``` is default (designating the characteristic of $A$)
  1. ```"gen"``` - general case $\rightarrow$ LU decomposition $\rightarrow$ Lapack - gesv 
  2. ```"sym"``` - symmetric (complex symmetric also, note that this is not Hermitian) case $\rightarrow$ diagonal pivoting $\rightarrow$ Lapack - sysv
  3. ```"her"``` - Hermitian matrix case $\rightarrow$ diagonal pivoting $\rightarrow$ Lapack - hesv
  4. ```"pos"``` - positive definite matrix case $\rightarrow$ Cholesky decomposition $\rightarrow$ Lapack - posv
    * **(!!!)** even if the wrong argument is given, ```linalg.slove``` does not show error message!
    * Therefore if you have no idea about the characteristic of the matrix, use "gen"

$$
\mathbf{b} = 
\begin{bmatrix}
1 \\
1 \\
1
\end{bmatrix}, \quad
A_{\text{singular}} = 
\begin{bmatrix}
1 & 3 & 4 \\
-4 & 2 & -6 \\
-3 & -2 & -7
\end{bmatrix}, \quad
A_{\text{gen}} =
\begin{bmatrix}
0 & 1 & 2 \\
1 & 0 & 3 \\
4 & -3 & 8
\end{bmatrix}, \quad
A_{\text{sym}} =
\begin{bmatrix}
1 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 1
\end{bmatrix}
$$

$$
A_{\text{sym (complex)}} =
\begin{bmatrix}
1 & 2 - i & 1 + 2i \\
2 - i & 1 & 3 \\
1 + 2i & 3 & 1
\end{bmatrix}, \quad
A_{\text{her}} =
\begin{bmatrix}
1 & 2 + i & 1 - 2i \\
2 - i & 1 & 3 \\
1 + 2i & 3 & 1
\end{bmatrix}, \quad
A_{\text{pos}} =
\begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2
\end{bmatrix}
$$

In [6]:
# Vector b
b = np.ones(3)

# Singular matrix
A_sing = np.array([
    [1, 3, 4],
    [-4, 2, -6],
    [-3, -2, -7]
])

# General matrix
A_gen = np.array([
    [0, 1, 2],
    [1, 0, 3],
    [4, -3, 8]
])

# Symmetric matrix
A_sym = np.array([
    [1, 2, 1],
    [2, 1, 3],
    [1, 3, 1]
])

# Symmetric (complex) matrix
A_sym_c = np.array([
    [1, 2 - 1j, 1 + 2j],
    [2 - 1j, 1, 3],
    [1 + 2j, 3, 1]
])

# Hermitian matrix
A_her = np.array([
    [1, 2 + 1j, 1 - 2j],
    [2 - 1j, 1, 3],
    [1 + 2j, 3, 1]
])

# Positive definite matrix
A_pos = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])

Case 1. Singular Matrix $\rightarrow$ error

In [7]:
x = linalg.solve(A_sing, b) # singular

LinAlgError: Matrix is singular.

Case 2. general case

In [8]:
x = linalg.solve(A_gen, b) 

In [9]:
# check for numeric error
A_gen @ x - b

array([0., 0., 0.])

Case 3. symmetric matrix

In [10]:
# "gen"
x = linalg.solve(A_sym, b) 

# check for numeric error
A_sym @ x - b

array([0., 0., 0.])

In [11]:
# "sym"
x = linalg.solve(A_sym, b, assume_a = "sym") 

# check for numeric error
A_sym @ x - b

array([0., 0., 0.])

In [12]:
# "pos" # WRONG
x = linalg.solve(A_sym, b, assume_a = "pos") 

# check for numeric error
A_sym @ x - b

LinAlgError: Matrix is singular.

Case 4. complex symmetric matrix

In [13]:
# "sym"
x = linalg.solve(A_sym_c, b, assume_a = "sym") 

# check for numeric error # very small! (, which is good)
A_sym_c @ x - b

array([0.00000000e+00+5.55111512e-17j, 2.22044605e-16+1.94289029e-16j,
       0.00000000e+00+1.24900090e-16j])

In [14]:
# "gen" # not ideal but ok
x = linalg.solve(A_sym_c, b, assume_a = "gen") 

# check for numeric error # very small! (, which is good)
A_sym_c @ x - b

array([0.-5.55111512e-17j, 0.+0.00000000e+00j, 0.+0.00000000e+00j])

Case 5. Hermitian matrix

In [15]:
# "her"
x = linalg.solve(A_her, b, assume_a = "her") 

# check for numeric error # very small! (, which is good)
A_her @ x - b

array([ 0.00000000e+00+0.00000000e+00j, -4.44089210e-16+1.94289029e-16j,
        2.22044605e-16-1.66533454e-16j])

In [16]:
# "gen" # not optimal but ok
x = linalg.solve(A_her, b, assume_a = "gen") 

# check for numeric error # very small! (, which is good)
A_her @ x - b

array([0.-5.55111512e-17j, 0.+0.00000000e+00j, 0.+0.00000000e+00j])

Case 6. positive definite matrix

In [17]:
# "pos"
x = linalg.solve(A_pos, b, assume_a = "pos") 

# check for numeric error # very small! (, which is good)
A_pos @ x - b

array([-8.88178420e-16,  1.55431223e-15, -4.44089210e-16])

In [18]:
# "gen" # not ideal but ok
x = linalg.solve(A_pos, b, assume_a = "gen") 

# check for numeric error # very small! (, which is good)
A_pos @ x - b

array([ 0.00000000e+00,  2.22044605e-16, -4.44089210e-16])

## 3.2 Triangular Matrix Solver

```python
x = linalg.slove_triangular(A, b, lower = False)
```

* algorithm: backsubstitution
* upper triangular is default
* Lapack - trtrs

$$
A = 
\begin{bmatrix}
1 & 0 & 0 & 0 \\
1 & 4 & 0 & 0 \\
5 & 0 & 1 & 0 \\
8 & 1 & -2 & 2
\end{bmatrix}, \quad
b = 
\begin{bmatrix}
1 \\
2 \\
3 \\
4
\end{bmatrix}
$$

In [19]:
# Define matrix A
A = np.array([
    [1, 0, 0, 0],
    [1, 4, 0, 0],
    [5, 0, 1, 0],
    [8, 1, -2, 2]
], dtype = np.float64)

# Define vector b
b = np.array([1, 2, 3, 4], dtype = np.float64)

In [20]:
x = linalg.solve_triangular(A, b, lower = True)

In [21]:
# check for numeric error # very small! (, which is good)
A @ x - b

array([0., 0., 0., 0.])

# 4. Systemic Way to Check for Numeric Accuracy

```python
bool_close = np.allclose(A@x, b)
bool_close = np.allclose(A@x - b, np.zeros(((b.shape[0],)))
bool_close = np.allclose(A@x - b, np.zeros((b.size))
```

```np.allclose``` criteria:
$$
|x - y| \leq \left( \varepsilon_1 + \varepsilon_2 |y| \right)
$$

- $\varepsilon_1 = 10^{-8}$: absolute difference  
- $\varepsilon_2 = 10^{-5}$: relative difference

$$
A_{\text{pos}} =
\begin{bmatrix}
2 & -1 & 0 \\
-1 & 2 & -1 \\
0 & -1 & 2
\end{bmatrix}, \quad
\mathbf{b} =
\begin{bmatrix}
1 \\
1 \\
1
\end{bmatrix}
$$

In [22]:
A = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
])

b = np.array([1, 1, 1])

In [23]:
x = linalg.solve(A, b, assume_a = "pos")

You can check the absolute difference manually

In [24]:
A@x - b

array([-8.88178420e-16,  1.55431223e-15, -4.44089210e-16])

Or you can use ```np.allclose```

In [25]:
zr = np.zeros(3, dtype = np.float64)

In [26]:
bool_close = np.allclose(A@x - b, zr)
print(bool_close)

True


# Practice 1.

$$
A =
\begin{bmatrix}
1 & \frac{1}{2} & \frac{1}{3} & \cdots & \frac{1}{9} & \frac{1}{10} \\
\frac{1}{2} & \frac{1}{3} & \frac{1}{4} & \cdots & \frac{1}{10} & \frac{1}{11} \\
\frac{1}{3} & \frac{1}{4} & \frac{1}{5} & \cdots & \frac{1}{11} & \frac{1}{12} \\
\vdots & \vdots & \vdots & \ddots & \vdots & \vdots \\
\frac{1}{9} & \frac{1}{10} & \frac{1}{11} & \cdots & \frac{1}{17} & \frac{1}{18} \\
\frac{1}{10} & \frac{1}{11} & \frac{1}{12} & \cdots & \frac{1}{18} & \frac{1}{19}
\end{bmatrix}
$$

You can create 10 x 10 Hilbert matrix with ```linalg.hilbert(10)```

1. Define A
2. Compute inv_A
3. x1 = inv_A @ b (b is size 10 random vector)
4. x2 with ```linalg.solve``` (gen)
5. A@x1 - b
6. A@x2 - b
7. A@x1 - b, A@x2 - b $\rightarrow$ compare them with zero vectors with ```np.allclose```

(Hilbert matrices are known to be difficult to solve using numerical methods - "ill-conditioned")

In [27]:
A = linalg.hilbert(10)
b = np.random.rand(10)

In [28]:
inv_A = linalg.inv(A)

In [29]:
x1 = inv_A @ b
x2 = linalg.solve(A, b, assume_a = "gen")

In [30]:
A@x1 - b

array([ 7.82620030e-05,  5.36797948e-06, -3.64331512e-05, -5.32287173e-05,
       -9.73738462e-05, -9.68858811e-05, -9.63069908e-05, -8.60768432e-05,
       -6.34982371e-05, -7.19347468e-05])

In [31]:
A@x2 - b

array([-3.61789150e-05,  5.36797948e-06,  2.46020050e-05,  7.80643890e-06,
       -9.63580906e-06, -1.29625412e-05, -1.61983482e-05, -2.15350337e-06,
       -1.39071726e-05, -7.08489325e-06])

In [32]:
np.allclose(A@x1 - b, A@x2 - b) # False!

False