In [1]:
import numpy as np
from scipy import linalg

# 1. Eigenvalues and Eigenvectors

Eigenvalue problems and Generalized eigenvalue problems; in this document, we focus on the orginal eigenvalue problems. Also, left eigenvectors are out of the scop of this document.

$$
A \mathbf{x} = \lambda \mathbf{x}, \quad A \mathbf{x} = \lambda M \mathbf{x}
$$



```python
eigvals, eigvecs = linalg.eig(A)    # for eigenvalue problems
eigvals, eigvecs = linalg.eig(A, M) # for generalized eigenvalue problems
```
* ```eigval``` - 1D array (vector)
* ```eigvecs``` - 2D array with each eigvec as a columnvector
* corresponding Lapack function
  1. geev (eigenvalue problems)
  2. ggev (generalized eigenvalue problems)

How ```geev``` is structured?

1) balancing (gebal) - to reduce the norm
2) upper Hessenberg (gehrd) - using Householder method
3) real orthogonal matrix from Hessenberg (orghr) or complex unitary matrix from Hessenberg (unghr)
4) Schur factorization, QR algorithm (hseqr)

To elaborate on 3),
The Hessenberg matrix, $H$ is similar to $A$,

$$
A = U^{\top}HU
$$

The orthogonal matrix or complex unitary matrix refers to $U$.

To elaborate on 4),
as we seen in the previous document, QR factorization happens multiple times. If we refer to all the $Q_k$s as $Q_1, Q_2, \cdots Q_k, \quad$ $UQ_0Q_1 \cdots Q_k$ becomes the eigenvector matrix.

Example

$$
A = \begin{bmatrix} 0 & -1 \\ 1 & 0 \end{bmatrix}
$$

\begin{align*}
\lambda_1 = i, \quad \mathbf{v}_1 = \begin{bmatrix} 1 \\ -i \end{bmatrix} \\
\lambda_2 = -i, \quad \mathbf{v}_2 = \begin{bmatrix} 1 \\ i \end{bmatrix}
\end{align*}

(For the sake of simplicity, I did not normalized the vectors but actual results would be normalized ones.)

```eigvals = [1j, -1j]```, 
```eigvecs = [[1, 1], [-1j, 1j]]```, ```v1 = eigvecs[:, 0]```, ```v2 = eigvecs[:, 1]```

Double-check?

$$
A \begin{bmatrix} \mathbf{v}_1 & \mathbf{v}_2 \end{bmatrix} =
\begin{bmatrix} \mathbf{v}_1 & \mathbf{v}_2 \end{bmatrix}
\begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix}
=
\begin{bmatrix} \lambda_1 \mathbf{v}_1 & \lambda_2 \mathbf{v}_2 \end{bmatrix}
$$

```python
#LHS
A @ eigvecs

#RHS
eigvecs @ np.diag(eigvals)

#RHS
eicvecs * eigvals # computational advantage
```

Or simply, one can check the following equation:

$$
A \mathbf{v}_1 = \lambda_1 \mathbf{v}_1
$$

```python
#LHS
A @ eigvecs[:,0]

#RHS
eigvals[0] * eigvecs[:,0]
```

In [11]:
A = np.array([
[0, -1],
[1, 0]
])
print(A)

[[ 0 -1]
 [ 1  0]]


In [3]:
eigvals, eigvecs = linalg.eig(A)
print(eigvals)
print()
print(eigvecs)

[0.+1.j 0.-1.j]

[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [4]:
# double-check

np.allclose(A @ eigvecs, eigvecs * eigvals)

True

In [5]:
# the result is normalized vectors

v1 = eigvecs[:, 0]
print(linalg.norm(v1))
print()
print(np.allclose(1, linalg.norm(v1)))

0.9999999999999999

True


## 1.1 Eigenvalues Only

```python
eigvals = linalg.eig(A, right = False)    # for eigenvalue problems
eigvals = linalg.eig(A, M, right = False) # for generalized eigenvalue problems
```

In [13]:
A = np.array([
[0, -1],
[1, 0]
])
print(A)

[[ 0 -1]
 [ 1  0]]


In [14]:
eigvals = linalg.eig(A, right = False)
print(eigvals)

[0.+1.j 0.-1.j]


# 2. For symmetric / Hermitian Matrices

Eigenvalue problems and Generalized eigenvalue problems; now $A$ is either **symmetric or Hermitian matrix** and $M$ is **positive definite** matrix. All eigenvalues are **real**.
 
$$
A \mathbf{x} = \lambda \mathbf{x}, \quad A \mathbf{x} = \lambda M \mathbf{x}
$$



```python
eigvals, eigvecs = linalg.eigh(A)    # for eigenvalue problems
eigvals, eigvecs = linalg.eigh(A, M) # for generalized eigenvalue problems
```
* ```eigval``` - 1D array (vector)
* ```eigvecs``` - 2D array with each eigvec as a columnvector
* corresponding Lapack function
  1. syevr (symmetric)
  2. heevr (Hermitian)
  3. sygvd (symmetric, generalized)
  4. hegvd (Hermitian, generalized)

How the Lapack functions are structured? (for generalized problems, they are structured differently. Not covered in this document)

1) reduction to tridiagonal form using Householder method - sytrd, hetrd
2) Instead of QR algorithm, in this case use dqds algorithm and Relatively Robust Representations (rrr method) - stemr, ormtr, unmtr

(Focus on how to use the functions instead.)

## 2.1 Eigenvalues Only

```python
eigvals = linalg.eigh(A, eigvals_only = False)    # for eigenvalue problems
eigvals = linalg.eigh(A, M, eigvals_only = False) # for generalized eigenvalue problems
```

Example

$$
A =
\begin{bmatrix}
6 & 3 & 1 & 5 \\
3 & 0 & 5 & 1 \\
1 & 5 & 6 & 2 \\
5 & 1 & 2 & 2
\end{bmatrix}
$$

In [15]:
A = np.array([
    [6, 3, 1, 5],
    [3, 0, 5, 1],
    [1, 5, 6, 2],
    [5, 1, 2, 2]
])

print(A)

[[6 3 1 5]
 [3 0 5 1]
 [1 5 6 2]
 [5 1 2 2]]


In [16]:
eigvals, eigvecs = linalg.eigh(A)

In [17]:
print(eigvals)
print()
print(eigvecs)

[-3.74637491 -0.76263923  6.08502336 12.42399079]

[[ 0.35986577 -0.40700525  0.58177024 -0.60529888]
 [-0.76481823 -0.44157496 -0.24929195 -0.39738916]
 [ 0.42255936  0.15465567 -0.7128596  -0.53791859]
 [-0.32709828  0.78449978  0.3020399  -0.43166968]]


In [18]:
eigvals = linalg.eigh(A, eigvals_only = True)
print(eigvals)

[-3.74637491 -0.76263923  6.08502336 12.42399079]


In [19]:
# double-check

np.allclose(A @ eigvecs, eigvecs * eigvals)

True

## 2.2 Computational Costs: ```eigh``` vs ```eig```

In [20]:
import timeit

In [43]:
A = np.random.rand(1000, 1000)
A = (A + A.T) # symmetric matrix

In [44]:
# eigh

start = timeit.default_timer()
eigvals, eigvecs = linalg.eigh(A)
end = timeit.default_timer()
comp_time = end - start
print(comp_time)

0.2566898000004585


In [45]:
# eig

start = timeit.default_timer()
eigvals, eigvecs = linalg.eig(A)
end = timeit.default_timer()
comp_time = end - start
print(comp_time)

0.6802019999995537


## 2.3 Is there a way to use QR algorithm?

Lapack: syev, heev

You can build a custom function using the above Lapack function.
In building the such function, use 

```python
linalg.get_lapack_func
```

But actually, for ```linalg.eigh``` is usually faster and more stable.

# Practice

\begin{bmatrix}
2 & 1 & 1 &  &  &  \\
1 & 2 & 1 & 1 &  &  \\
1 & 1 & 2 & 1 & 1 &  \\
 & 1 & 1 & \ddots & \ddots &  \\
 &  & 1 & \ddots & 2 & 1 \\
 &  &  & 1 & 1 & 2
\end{bmatrix}

1. Make the matrix using numpy functions
2. Get eigenvalues and eigenvectors with ```eig``` and ```eigh``` and compare the time

In [49]:
A = 2 * np.eye(1000) + np.eye(1000, k = 1) + np.eye(1000, k = 2) + np.eye(1000, k = -1) + np.eye(1000, k = -2)
print(A)

[[2. 1. 1. ... 0. 0. 0.]
 [1. 2. 1. ... 0. 0. 0.]
 [1. 1. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 2. 1. 1.]
 [0. 0. 0. ... 1. 2. 1.]
 [0. 0. 0. ... 1. 1. 2.]]


In [50]:
# eigh

start = timeit.default_timer()
eigvals, eigvecs = linalg.eigh(A)
end = timeit.default_timer()
comp_time = end - start
print(comp_time)

0.19478009999875212


In [51]:
# eig

start = timeit.default_timer()
eigvals, eigvecs = linalg.eig(A)
end = timeit.default_timer()
comp_time = end - start
print(comp_time)

0.7200082000017574
