In [1]:
import numpy as np
from scipy import linalg

# 1. LU Decomposition (```linalg.lu```)

$$
A = LU, \quad A = PLU
$$

$P$ is the permutation matrix to interchange rows for LU decomposition.


```python
P, L, U = linalg.lu(A)
```
* ```P``` - Permutation Matrix
* ```L``` - Lower Triangular Matrix
* ```U``` - Upper Triangular Matrix

Example:

$$
A = 
\begin{bmatrix}
2 & 4 & -1 & 5 & -2 \\
-4 & -5 & 3 & -8 & 1 \\
2 & -5 & -4 & 1 & 8 \\
-6 & 0 & 7 & -3 & 1\\
\end{bmatrix}, \;
LU = 
\begin{bmatrix}
-6 & 0 & 7 & -3 & 1\\
-4 & -5 & 3 & -8 & 1 \\
2 & -5 & -4 & 1 & 8 \\
2 & 4 & -1 & 5 & -2 \\
\end{bmatrix}, \;
P = 
\begin{bmatrix}
0 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
1 & 0 & 0 & 0\\
\end{bmatrix}
$$

In [2]:
A = np.array([
    [2, 4, -1, 5, -2],
    [-4, -5, 3, -8, 1],
    [2, -5, -4, 1, 8],
    [-6, 0, 7, -3, 1]
])

In [3]:
P, L, U = linalg.lu(A)

In [4]:
print(f'P = {P}')

P = [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [5]:
print(f'LU = {L@U}')

LU = [[-6.  0.  7. -3.  1.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [ 2.  4. -1.  5. -2.]]


In [6]:
print(f'A == {P@L@U}')

A == [[ 2.  4. -1.  5. -2.]
 [-4. -5.  3. -8.  1.]
 [ 2. -5. -4.  1.  8.]
 [-6.  0.  7. -3.  1.]]


# 2. LU Decomposition for Solver (```linalg.lu_factor```)

```python
lu, piv = linalg.lu_factor(A)
```
* ```lu``` - L and U are stored as one matrix
* ```piv``` - 1D array storing information on row interchange (```piv[i]```: ith row is interchanged with the piv[i]'th row)



Example:

$$
A = 
\begin{bmatrix}
7 & 5 & 6 & 6\\
1 & 2 & 2 & 8\\
5 & 4 & 4 & 8\\
9 & 5 & 8 & 7\\
\end{bmatrix}, \quad
L = 
\begin{bmatrix}
1 & 0 & 0 & 0\\
0.111 & 1 & 0 & 0\\
0.556 & 0.846 & 1 & 0\\
0.778 & 0.769 & 0.778 &1 \\
\end{bmatrix}, \quad
U = 
\begin{bmatrix}
9 & 5 & 8 & 7\\
0 & 1.444 & 1.111 & 7.222\\
0 & 0 & -1.385 & -2\\
0 & 0 & 0 & -3.444\\
\end{bmatrix}, \quad
LU = 
\begin{bmatrix}
9 & 5 & 8 & 7\\
1 & 2 & 2 & 8\\
5 & 4 & 4 & 8\\
7 & 5 & 6 & 6\\
\end{bmatrix}, \quad
P = 
\begin{bmatrix}
0 & 0 & 0 & 1\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
1 & 0 & 0 & 0\\
\end{bmatrix}
$$

```lu``` - $L$ and $U$ are stored altogether

$$
\begin{bmatrix}
9 & 5 & 8 & 7\\
0.111 & 1.444 & 1.111 & 7.222\\
0.556 & 0.846& -1.385 & -2\\
0.778 & 0.769 & 0.778 & -3.444\\
\end{bmatrix}
$$

* ```L = np.tril(lu, k =-1) + np.eye(lu.shape[0], lu.shape[1])``` - Reconstructing $L$ from ```lu```\
* ```U = np.triu(lu, k =0)``` - Reconstructing $U$ from ```lu```

```piv``` - information on row interchange

$$
\begin{bmatrix}
3, & 1, & 2, & 3\\
\end{bmatrix}
$$

(Applied sequentially)

* ```piv[0] = 3``` row 0 <-> row 3
* ```piv[1] = 1``` row 1 <-> row 1 (no change)
* ```piv[2] = 2``` row 2 <-> row 2 (no change)
* ```piv[3] = 3``` row 3' <-> row 3 (current row 3'  was previously row 0)

Note that ```piv``` represents permutation, $\begin{bmatrix}
3, & 1, & 2, & 0\\
\end{bmatrix}$

In [7]:
A = np.array([
    [7, 5, 6, 6],
    [1, 2, 2, 8],
    [5, 4, 4, 8],
    [9, 5, 8, 7]
], dtype=np.float64)

In [8]:
lu, piv = linalg.lu_factor(A)

In [9]:
# Check the values
print(lu)

[[ 9.          5.          8.          7.        ]
 [ 0.11111111  1.44444444  1.11111111  7.22222222]
 [ 0.55555556  0.84615385 -1.38461538 -2.        ]
 [ 0.77777778  0.76923077  0.77777778 -3.44444444]]


In [10]:
# Check the values
print(piv)

[3 1 2 3]


In [11]:
# Reconstruct L from lu
L = np.tril(lu, k=-1) + np.identity(4)
L

array([[1.        , 0.        , 0.        , 0.        ],
       [0.11111111, 1.        , 0.        , 0.        ],
       [0.55555556, 0.84615385, 1.        , 0.        ],
       [0.77777778, 0.76923077, 0.77777778, 1.        ]])

In [12]:
# Reconstruct U from lu
U = np.triu(lu, k=0)
U

array([[ 9.        ,  5.        ,  8.        ,  7.        ],
       [ 0.        ,  1.44444444,  1.11111111,  7.22222222],
       [ 0.        ,  0.        , -1.38461538, -2.        ],
       [ 0.        ,  0.        ,  0.        , -3.44444444]])

In [13]:
# The rows are interchanged, right?
print(L@U)

[[9. 5. 8. 7.]
 [1. 2. 2. 8.]
 [5. 4. 4. 8.]
 [7. 5. 6. 6.]]


In [14]:
""" premutation from piv """
""" Reference: https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html """ 
def pivot_to_permutation(piv):
    perm = np.arange(len(piv))
    for i in range(len(piv)):
        perm[i], perm[piv[i]] = perm[piv[i]], perm[i]
    return perm
perm = pivot_to_permutation(piv)
print(perm)

[3 1 2 0]


In [15]:
# Reconstructing P
P = np.identity(4)[perm, :]
P

array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [16]:
# Reconstructing A
A_re = (L@U)[perm, :] # or P@L@U
A_re

array([[7., 5., 6., 6.],
       [1., 2., 2., 8.],
       [5., 4., 4., 8.],
       [9., 5., 8., 7.]])

In [17]:
# Sanity check
print(np.allclose(A, A_re))

True


# 3. LU Decomposition Solver (```linalg.lu_solve```)

We are going to use the results from ```linalg.lu_factor``` to solve a matrix equation, $AX = \mathbf{b}$.

```python
x = linalg.lu_solve((lu, piv), b) #lu, piv from linalg.lu_factor(A)
```

* corresponding Lapack function
  1. gettrf (linalg.lu_factor)
  2. gettrs (linalg.lu_solve)

Example:

$$
A\mathbf{x} = \mathbf{b}
$$

$$
A = 
\begin{bmatrix}
7 & 5 & 6 & 6\\
1 & 2 & 2 & 8\\
5 & 4 & 4 & 8\\
9 & 5 & 8 & 7\\
\end{bmatrix}, \quad
\mathbf{b} =
\begin{bmatrix}
1 \\
1 \\
1 \\
1 \\
\end{bmatrix}
$$

In [18]:
A = np.array([
    [7, 5, 6, 6],
    [1, 2, 2, 8],
    [5, 4, 4, 8],
    [9, 5, 8, 7]
], dtype=np.float64)

b = np.ones((4, ))

lu, piv = linalg.lu_factor(A)

# solution
x = linalg.lu_solve((lu, piv), b)

print(x)

[-0.16129032  0.19354839  0.12903226  0.06451613]


In [19]:
# Sanity check
np.allclose(A@x, b) 

True

### Performance comparison

Performance improvement is pronounced for iterative computations for large matrices.

```lu, piv = linalg.lu_factor(A)``` - $n^3$ $- (1)$, 
```x = linalg.lu_solve((lu, piv), b)``` - $n^2$ $-(2)$

* Decomposition one time (1)
* For different $\mathbf{b}$'s run (2), which is $n^2$

```x = linalg.solve(A, b)``` - $n^3$ $-(3)$

* For different $\mathbf{b}$'s run (3), which is $n^3$

Example:

$$
A =
\begin{bmatrix}
5 & 1 &        &        &        \\
1 & 5 & 1     &        &        \\
   & 1 & 5     & \ddots &        \\
   &    & \ddots & \ddots & 1     \\
   &    &        & 1     & 5
\end{bmatrix}_{1000 \times 1000}
$$
, calculate 10,000 times

```lu, piv = linalg.lu_factor(A)``` - $n^3$ $- (1)$
```x = linalg.lu_solve((lu, piv), b)``` - $n^2$ $-(2)$
$\rightarrow$ about 1.8 seconds

```x = linalg.solve(A, b)``` - $n^3$ $-(3)$
$\rightarrow$ about 125 seconds

Use band matrix functions $\rightarrow$ about 0.24 seconds (More advnaced method.. later will be covered.)

*We are going to test this at the end.*

# 4. Diagonal Pivoting Method (Bunch-Kaufman method)

$$
PAP^\top = LDL^\top, \quad PAP^\top = UDU^\top \; \text{(4)}
$$

$$
A = \tilde{L}D\tilde{L}^\top, \quad A = \tilde{U}D\tilde{U}^\top \; \text{(4)'}
$$

where $A$: symmetric and/or complex symmetric


$$
PAP^\top = LDL^H, \quad PAP^\top = UDU^H \; \text{(5)}
$$

$$
A = \tilde{L}D\tilde{L}^H, \quad A = \tilde{U}D\tilde{U}^H \; \text{(5)}
$$

where $A$: Hermitian, ($^H$: transpose conjugate)

also,

$D$: block diagonal matrix with the max size of block $2 \times 2$, symmetric and/or Hermitian \
$P$: permutation matrix \
$L,\: (U)$: lower (or upper) triangular matrix (diagonal = 1)\
$\tilde{L},\: (\tilde{U})$: permuatated lower (or upper) triangular matrix (diagonal = 1) 

```python
L, D, perm = linalg.ldl(A, lower=True, hermitian=True)   # L~DL~^H
L, D, perm = linalg.ldl(A, lower=True, hermitian=False)  # L~DL~^T
U, D, perm = linalg.ldl(A, lower=False, hermitian=True)  # U~DU~^H
U, D, perm = linalg.ldl(A, lower=False, hermitian=False) # U~DU~^T
```

```A = L @ D @ L.T``` - wrong

``````A[perm,:][:,perm] = L[perm,:] @ D @ L[:, perm]`````` - correct (Note. $(4)$)

**Downside:**

In previous sections, for LU decomposition along with ```linalg.lu```, ```linalg.lu_factor``` and ```linalg.lu_solve``` were provided for solving matrix equations. However, for ```linalg.ldl```, no such solver functions are offered in scipy yet. So, for the time being we have to stick to  ```linalg.lu_factor``` and ```linalg.lu_solve```.

Example:

In [20]:
# (Real) Symmetric
A1 = np.array([
    [9, 1, 1],
    [1, 0, -1],
    [1, -1, 4]
], dtype=np.float64)

# Hermitian
A2 = np.array([
    [9, 1-1j, 1],
    [1+1j, 0, -1+2j],
    [1, -1-2j, 4]
], dtype=np.complex128)

# Complex Symmetric
A3 = np.array([
    [9, 1+1j, 1],
    [1+1j, 0, -1+2j],
    [1, -1+2j, 4]
], dtype=np.complex128)

Case1 - A1 (Symmetric, real)

In [21]:
L_tilde, D, perm = linalg.ldl(A1, lower=True)
print(f'D = ')
print(D)
print()
print(f'L_tilde =') # permutated L
print(L_tilde)
print()
print(f'perm = {perm}')

D = 
[[ 9.          0.          0.        ]
 [ 0.          3.88888889  0.        ]
 [ 0.          0.         -0.42857143]]

L_tilde =
[[ 1.          0.          0.        ]
 [ 0.11111111 -0.28571429  1.        ]
 [ 0.11111111  1.          0.        ]]

perm = [0 2 1]


In [22]:
PA1P = A1[perm,:][:,perm]
print('PAP=')
print(PA1P)

PAP=
[[ 9.  1.  1.]
 [ 1.  4. -1.]
 [ 1. -1.  0.]]


In [23]:
# or equivalently
P = np.identity(3)[perm,:]
PA1P = P@A1@P.T
print('PAP=')
print(PA1P)

PAP=
[[ 9.  1.  1.]
 [ 1.  4. -1.]
 [ 1. -1.  0.]]


In [24]:
L = L_tilde[perm,:] # or equivalently L = P @ L_tilde
print(L)

[[ 1.          0.          0.        ]
 [ 0.11111111  1.          0.        ]
 [ 0.11111111 -0.28571429  1.        ]]


In [25]:
lhs = PA1P
rhs = L @ D @ L.conjugate().T

print(f'PA1P = LDL^T: {np.allclose(lhs, rhs)}')

PA1P = LDL^T: True


Case2 - A2 (Hermitian)

In [26]:
L_tilde, D, perm = linalg.ldl(A2, lower=True, hermitian=True)
PA2P = A2[perm,:][:,perm]
L = L_tilde[perm,:]

lhs = PA2P
rhs = L @ D @ L.conjugate().T
print(f'PA2P = LDL^T: {np.allclose(lhs, rhs)}')

PA2P = LDL^T: True


Case3 - A3 (Complex Symmetric)

In [27]:
L_tilde, D, perm = linalg.ldl(A3, lower=True, hermitian=False) # False
PA3P = A3[perm,:][:,perm]
L = L_tilde[perm,:]

lhs = PA3P
rhs = L @ D @ L.T #(no conjugate)
print(f'PA3P = LDL^T: {np.allclose(lhs, rhs)}')

PA3P = LDL^T: True


### Practice - Performance comparison

Example:

$$
A =
\begin{bmatrix}
5 & 1 &        &        &        \\
1 & 5 & 1     &        &        \\
   & 1 & 5     & \ddots &        \\
   &    & \ddots & \ddots & 1     \\
   &    &        & 1     & 5
\end{bmatrix}_{1000 \times 1000}
$$
, calculate 1,000 times

In [28]:
off_diag = np.ones((999, ))
A = 5*np.identity(1000) + np.diag(off_diag, k=1) + np.diag(off_diag, k=-1)

In [29]:
b = np.ones((1000,))

In [30]:
import timeit

In [31]:
n = 1000

In [32]:
"""linalg.lu_factor, linalg.lu_solve"""

###
start = timeit.default_timer()
###

lu, piv = linalg.lu_factor(A)

for _ in range(n):
    x = linalg.lu_solve((lu, piv), b)

###
end = timeit.default_timer()
###

print(f'{end-start: .6f}')

 0.230591


In [33]:
"""linalg.solve"""

###
start = timeit.default_timer()
###

for _ in range(n):
    x = linalg.solve(A, b)

###
end = timeit.default_timer()
###

print(f'{end-start: .6f}')

 1.253580


Take note of the computation times' difference.