# Basic Numpy Functions

In [1]:
import numpy as np

# 1. Identity Matrix

## 1.1 np.eye

**np.eye** - identity matrix with adjusting features (shifting)

```python
a = np.eye(2, 3, k = 1, dtype = ...)
```
first argument  : # of row\
second argument : # of col (default: same as # of row)\
thrid argument  : shifts  (default: k = 0)\
fourth argument : np.float64, np.complex128 

```python
np.eye(2)
```
* 2 x 2 identity matrix

```python
np.eye(2, 3)
```
* 2 x 3 matrix containing 2 x 2 identity submatrix

```python
np.eye(2, 3, k = 1)
```
* 2 x 3 matrix containing 2 x 2 identity submatrix
* shift the diagonal upward (if positive) or downward (if negative)

example:

In [2]:
a = np.eye(4, 5, k = 0, dtype = np.float64)

In [3]:
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [4]:
a = np.eye(4, 5, k = 1, dtype = np.float64)

In [5]:
print(a)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [6]:
a = np.eye(4, 5, k = -1, dtype = np.float64)

In [7]:
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


## 1.2 np.identity

**np.identity** - identity matrix

```python
a = np.identity(2, dtype = ...)
```
first argument  : # of row and col (symmetric)\
second argument : np.float64, np.complex128 

Note : Basically same with np.eye with one argument and the data type argument

In [8]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 2. Triangular Matrix

## np.tri

**np.tri** - lower triangular matrix with adjusting features (shifting)

```python
a = np.tri(2, 3, k = 1, dtype = ...)
```

first argument  : # of row\
second argument : # of col (default: same as # of row)\
thrid argument  : shifts  (default: k = 0)\
fourth argument : np.float64, np.complex128 

Some examples. Let's try out 5 x 5 lower triangular matrix

In [10]:
a = np.tri(5)
print(a)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


If explicitly write all default arguments, it is as follows:

In [11]:
a = np.tri(5, 5, k = 0, dtype = np.float64)
print(a)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


The same goes for nonsymmetric matrices:

In [12]:
a = np.tri(7, 5, k = 0, dtype = np.float64)
print(a)

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
a = np.tri(5, 7, k = 0, dtype = np.float64)
print(a)

[[1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0.]]


Shifts

In [14]:
a = np.tri(5, 7, k = 2, dtype = np.float64)
print(a)

[[1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [15]:
a = np.tri(5, 7, k = -2, dtype = np.float64)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0.]]


# 3. Zero Matrix, One Matrix, Full Matrix, Random Matrix

## 3.1 np.zeros

**np.zeros** - zero matrix or zero vector

```python
a = np.zeros(shape)
```
argument  : dimension of the matrix - tuple (row, col)
* if the argument is given as simple integer, it returns a zero vector of that size

In [16]:
a = np.zeros((2, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


## 3.2 np.ones

```python
a = np.ones(shape, dtype = ...)
```
argument  : dimension of the matrix - tuple (row, col)
* if the argument is given as simple integer, it returns a 'one' vector of that size

In [18]:
a = np.ones((2, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
a = np.ones(3)
print(a)

[1. 1. 1.]


**Note. data type**

In [20]:
a = np.zeros((2, 3), dtype = np.complex128)
print(a)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [21]:
a = np.ones((2, 3), dtype = np.complex128)
print(a)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


## 3.3 np.full

```python
a = np.full(shape, value, dtype = ...)
```
first argument  : dimension of the matrix - tuple (row, col)
* if the argument is given as simple integer, it returns a 'one' vector of that size

second argument : the value to fill the matrix / vector

In [22]:
a = np.full((2, 3), 3 + 3j, dtype = np.complex128)
print(a)

[[3.+3.j 3.+3.j 3.+3.j]
 [3.+3.j 3.+3.j 3.+3.j]]


In [23]:
a = np.full((2, 3), 3, dtype = np.float64)
print(a)

[[3. 3. 3.]
 [3. 3. 3.]]


## 3.4 np.random.rand

```python
a = np.random.rand(row, col)
```
first argument  : row 
second argument : col

* note that unlike np.ones, np.zeros, np.full, it is not tuple argument.
* random values between 0 and 1
* NO data type argument

In [24]:
a = np.random.rand(4, 5)
print(a)

[[0.2130835  0.44752622 0.36140122 0.39324883 0.86994058]
 [0.28795633 0.45619178 0.48016131 0.93486167 0.9894533 ]
 [0.18992026 0.05421964 0.54935182 0.18228335 0.84254462]
 [0.49557464 0.08062889 0.80207078 0.9230117  0.8094167 ]]


In [25]:
a = np.random.rand(4, 5)
print(a) # diff vals

[[0.35772435 0.54259464 0.90193907 0.99638594 0.67260354]
 [0.16295924 0.6404327  0.85938747 0.54727466 0.09318642]
 [0.30758178 0.99130734 0.07917783 0.40583471 0.85757235]
 [0.23860649 0.40110159 0.88732974 0.00369012 0.20180654]]


# Practice 1

create 10 x 10 identity matrix

Option 1. np.eye

In [26]:
print(np.eye(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [27]:
print(np.eye(10, 10, k = 0, dtype = np.float64))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Option 2. np.identity

In [28]:
print(np.identity(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [29]:
print(np.identity(10, dtype = np.float64))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


# Practice 2

Use np.random.rand to create a 3 x 3 matrix where the real part is 0 and the imaginary part is 0i to 1i.

In [30]:
a = np.zeros((3, 3), dtype = np.complex128)
print(a)
# np.full((3, 3), 0, dtype = np.complex128)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [31]:
a2 = np.full((3, 3), 0, dtype = np.complex128)

In [32]:
b = np.random.rand(3, 3)
b = b * 1j

In [33]:
print(a + b)

[[0.+0.46817455j 0.+0.13021709j 0.+0.78173909j]
 [0.+0.32767727j 0.+0.11425092j 0.+0.85962753j]
 [0.+0.49275149j 0.+0.46746113j 0.+0.37687065j]]


In [34]:
print(a2 + b) # same deal

[[0.+0.46817455j 0.+0.13021709j 0.+0.78173909j]
 [0.+0.32767727j 0.+0.11425092j 0.+0.85962753j]
 [0.+0.49275149j 0.+0.46746113j 0.+0.37687065j]]
