# Basic Numpy Functions (cont'd)

In [1]:
import numpy as np

# 1. Copy Matrix/Vector

## np.copy

**np.copy** - copy a matrix or vector and create a new object

if we simply use equal sign as follows:

```python
b = a
```

b and a point to the same object. Meaning, if you change a such as

```python
a[1, 1] = 0
```

it affects b.

To avoid this matter, use np.copy

```python
b = np.copy(b)
```

example:

In [2]:
a = np.array([[1, 2.5, 3], [-1, -2, -1.5],[4, 5.5, 6]], dtype = np.float64)
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [3]:
b = a

In [4]:
a[1, 1] = 0
print(b) # b is changed

[[ 1.   2.5  3. ]
 [-1.   0.  -1.5]
 [ 4.   5.5  6. ]]


Instead, use np.copy this time.

In [5]:
a = np.array([[1, 2.5, 3], [-1, -2, -1.5],[4, 5.5, 6]], dtype = np.float64)
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [6]:
b = np.copy(a)

In [7]:
a[1, 1] = 0
print(b) # b is not changed

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


Summary

```python
b = a
```
* a and b point to the same memory

```python
b = np.copy(a)
```
* new memory space is allocated for b

# 2. Reshape

**np.reshape** - reshape, i.e., change the demension of the given matrix

```python
b = np.reshape(a, number or shape-tuple)
```
first argument  : matrix or vector\
second argument : reshape target 

**Note : b refers to the same memory space!!**

```python
# to avoid this
b = np.copy(np.reshape(a, number or shape-tuple))
```

**Note : when you want to reshape a, use:**

```python
a = np.reshape(a, number or shape-tuple)
```

example:

In [8]:
a = np.array([[1, 2.5, 3], [-1, -2, -1.5]], dtype = np.float64)
print(a)
print("dimension of a: ", a.shape)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]]
dimension of a:  (2, 3)


In [9]:
b = np.reshape(a, (3, 2))
print(b)
print("dimension of b: ", b.shape)

[[ 1.   2.5]
 [ 3.  -1. ]
 [-2.  -1.5]]
dimension of b:  (3, 2)


In [10]:
b = np.reshape(a, (-1, 6)) # when you are sure about the # of cols and want to avoid the errors
print(b)
print("dimension of b: ", b.shape)

[[ 1.   2.5  3.  -1.  -2.  -1.5]]
dimension of b:  (1, 6)


In [11]:
b = np.reshape(a, (6, -1)) # when you are sure about the # of rows
print(b)
print("dimension of b: ", b.shape)

[[ 1. ]
 [ 2.5]
 [ 3. ]
 [-1. ]
 [-2. ]
 [-1.5]]
dimension of b:  (6, 1)


In [12]:
b = np.reshape(a, 6)
print(b)
print("dimension of b: ", b.shape)

[ 1.   2.5  3.  -1.  -2.  -1.5]
dimension of b:  (6,)


In [13]:
b = np.reshape(a, -1)
print(b)
print("dimension of b: ", b.shape)

[ 1.   2.5  3.  -1.  -2.  -1.5]
dimension of b:  (6,)


**b refers to the same space:**

In [14]:
a[1, 1] = 0

In [15]:
print(b) # b changed

[ 1.   2.5  3.  -1.   0.  -1.5]


In [16]:
a = np.array([[1, 2.5, 3], [-1, -2, -1.5]], dtype = np.float64)
b = np.copy(np.reshape(a, -1)) # np.copy
a[1, 1] = 0
print(b)
print("dimension of b: ", b.shape) # b has not changed

[ 1.   2.5  3.  -1.  -2.  -1.5]
dimension of b:  (6,)


# 3. Copying Triangular Entries

## 3.1 np.tril

**np.tril** - copying lower triangular entires with adjusting features (shifting)

```python
b = np.tril(a, k = band_id)
```
first arg: matrix to copy\
second arg: shifting parameter (default = 0)

## 3.2 np.triu

**np.triu** - copying upper triangular entires with adjusting features (shifting)

```python
b = np.triu(a, k = band_id)
```
first arg: matrix to copy\
second arg: shifting parameter (default = 0)

**Note.\
tril, triu allocate new memory space.**

In [17]:
a = np.random.rand(4, 6)
a = np.trunc(a * 100)
print(a)

[[ 2. 97. 74. 86. 98. 96.]
 [90. 50. 78. 57.  6. 94.]
 [54. 53. 67. 38. 91. 59.]
 [31. 67. 75. 66.  1. 88.]]


In [18]:
b1 = np.triu(a, k = 0) # k = 0 can be dropped
print(b1)

[[ 2. 97. 74. 86. 98. 96.]
 [ 0. 50. 78. 57.  6. 94.]
 [ 0.  0. 67. 38. 91. 59.]
 [ 0.  0.  0. 66.  1. 88.]]


In [19]:
b2 = np.triu(a, k = 1)
print(b2)

[[ 0. 97. 74. 86. 98. 96.]
 [ 0.  0. 78. 57.  6. 94.]
 [ 0.  0.  0. 38. 91. 59.]
 [ 0.  0.  0.  0.  1. 88.]]


In [20]:
b3 = np.triu(a, k = -1)
print(b3)

[[ 2. 97. 74. 86. 98. 96.]
 [90. 50. 78. 57.  6. 94.]
 [ 0. 53. 67. 38. 91. 59.]
 [ 0.  0. 75. 66.  1. 88.]]


In [21]:
c1 = np.tril(a, k = 0)
print(c1)

[[ 2.  0.  0.  0.  0.  0.]
 [90. 50.  0.  0.  0.  0.]
 [54. 53. 67.  0.  0.  0.]
 [31. 67. 75. 66.  0.  0.]]


In [22]:
c2 = np.tril(a, k = 1)
print(c2)

[[ 2. 97.  0.  0.  0.  0.]
 [90. 50. 78.  0.  0.  0.]
 [54. 53. 67. 38.  0.  0.]
 [31. 67. 75. 66.  1.  0.]]


In [23]:
c3 = np.tril(a, k = -1)
print(c3)

[[ 0.  0.  0.  0.  0.  0.]
 [90.  0.  0.  0.  0.  0.]
 [54. 53.  0.  0.  0.  0.]
 [31. 67. 75.  0.  0.  0.]]


In [24]:
c3[1, 0] = -10
print(c3)

[[  0.   0.   0.   0.   0.   0.]
 [-10.   0.   0.   0.   0.   0.]
 [ 54.  53.   0.   0.   0.   0.]
 [ 31.  67.  75.   0.   0.   0.]]


In [25]:
print(a) # no change in a

[[ 2. 97. 74. 86. 98. 96.]
 [90. 50. 78. 57.  6. 94.]
 [54. 53. 67. 38. 91. 59.]
 [31. 67. 75. 66.  1. 88.]]


# 4. Extracting Specific Band Vector from a Matrix

## np.diag

**np.diag** - band vector

```python
b = np.diag(a, k = 2)
```
argument  : matrix whose band vector is of interest (k is shifting parameter)

In [26]:
print(a)

[[ 2. 97. 74. 86. 98. 96.]
 [90. 50. 78. 57.  6. 94.]
 [54. 53. 67. 38. 91. 59.]
 [31. 67. 75. 66.  1. 88.]]


In [34]:
b1 = np.diag(a, k = 0)

In [35]:
print(b1)

[ 2. 50. 67. 66.]


In [36]:
b2 = np.diag(a, k = 1)
print(b2)

[97. 78. 38.  1.]


In [37]:
b3 = np.diag(a, k = -1)
print(b3)

[90. 53. 75.]


**Note.\
np.diag in this case DO NOT allocate new memory space.**

Therefore we make changes to a, it also changes to b's.

In [39]:
a[0, 0] = -100
print(b1) #changed

[-100.   50.   67.   66.]


The other way around is impossible. b's are read-only.

In [41]:
b1[0] = 2 # read-only 

ValueError: assignment destination is read-only

# 5. Creating a Sqaure Matrix from a Vector

## 5.1 np.diag

```python
a = np.diag(b, k = band_id)
```
argument  : vector to create a square matrix (k is shifting parameter)

In [48]:
b = np.array([1, 2, 3, 4], dtype = np.float64)
print(b)

[1. 2. 3. 4.]


In [49]:
a = np.diag(b, k = 0)
print(a)
print(a.shape)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
(4, 4)


In [50]:
a = np.diag(b, k = 1)
print(a)
print(a.shape)

[[0. 1. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]
(5, 5)


In [51]:
a = np.diag(b, k = 2)
print(a)
print(a.shape)

[[0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(6, 6)


In [52]:
a = np.diag(b, k = -1)
print(a)
print(a.shape)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]
(5, 5)


In [53]:
a = np.diag(b, k = -2)
print(a)
print(a.shape)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]]
(6, 6)


**Note.\
np.diag in this case DO allocate new memory space.**

In [54]:
b[1] = -100
print(a) # no change

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]]


## 5.2 np.diagflat

np.diag in one case extract a band vector from the 2D Array input, on the other creates a square matrix from the 1D Array input.

In contrast, np.diagflat creates a square matrix regardless of whether the input being 2D Array or 1D Array.

```python
a = np.diagflate(M, k = band_id)
```
argument  : either 1D Array or 2D Array

* 1D Array: same as np.diag
* 2D Array: convert the 2D Array into 1D Array and then use that 1D Array to form a square matrix

### 1D Array

In [56]:
b = np.array([1, 2, 3, 4], dtype = np.float64)
print(b)

[1. 2. 3. 4.]


In [57]:
a = np.diagflat(b, k = 0)
print(a)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


### 2D Array

In [62]:
a = np.random.rand(3, 3)
a = a * 10
a = np.trunc(a)
print(a)

[[4. 0. 3.]
 [8. 3. 6.]
 [0. 9. 9.]]


In [66]:
b = np.diagflat(a, k = 0)
print(b)
print(b.shape)

[[4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9.]]
(9, 9)


In [69]:
b = np.diagflat(a, k = 2)
print(b)
print(b.shape)

[[0. 0. 4. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 8. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(11, 11)


In [70]:
b = np.diagflat(a, k = -2)
print(b)
print(b.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]]
(11, 11)


**Note.\
np.diagflat DO NOT allocate new memory space.**

In [71]:
a[0, 0] = -100
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 8. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 6. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]]


# 6. Trace (sum of diagonals)

## np.trace

```python
b = np.trace(a, offset = band_id)
```
argument  : matrix to compute trace (offset is shifting parameter)

In [72]:
a = np.random.rand(3, 3)
a = a * 10
a = np.trunc(a)
print(a)

[[4. 8. 3.]
 [8. 6. 8.]
 [9. 6. 8.]]


In [73]:
b = np.trace(a) # offset = 0
print(b)

18.0


In [74]:
b = np.trace(a, offset = 1) # offset = 0
print(b)

16.0


In [75]:
b = np.trace(a, offset = -1) # offset = 0
print(b)

14.0


# 6. Flattening

## 6.1 .faltten()

```python
b = a.flatten()
```

* turn 2D Array into 1D Array (**NOT** same memory)

## 6.2 np.ravel

```python
b = np.ravel(a)
```

* turn 2D Array into 1D Array (**SAME** memory)

```python
b = np.copy(a.ravel()) # assign new memory
```

* basically same as a.flatten()

In [83]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [84]:
b1 = a.flatten()
b2 = np.copy(np.ravel(a))
b3 = np.copy(a.ravel())
b4 = np.ravel(a)
b5 = a.ravel()

In [85]:
a[0, 0] = -100

In [87]:
print(b1) # separate object
print(b2) # separate object
print(b3) # separate object
print(b4) # same object
print(b5) # same object

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[-100    2    3    4    5    6    7    8    9]
[-100    2    3    4    5    6    7    8    9]


## Practice

$$
a = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15
\end{bmatrix}
$$

1. initialize a
2. show the difference between '=' and np.copy
3. reshape a to 5 x 3 matrix
4. store the upper trianglur entries as a separate matrix, bt (k = 0)
5. turn bt into 1D Array and form a square matrix from it. Make sure the very 1D Array shows up in the band of the matrix.
6. compute the trace of the matrix.

1) Initialize a

In [88]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)


2. = and np.copy

In [93]:
b1 = a
b2 = np.copy(a)

In [94]:
b1 is b2 # False

False

In [95]:
a is b1  # True

True

In [96]:
a is b2  # False

False

3. reshape a to 5 x 3 matrix

In [98]:
a = np.reshape(a, (5, 3)) # a = np.resahpe(a, (5, -1)) or a = np.reshape(a, (-1, 3))

In [99]:
print(a)
print(a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
(5, 3)


4. store the upper trianglur entries as a separate matrix, bt (k = 0)

In [102]:
bt = np.triu(a, k = 0) # k = 0 can be dropped
print(bt)

[[1 2 3]
 [0 5 6]
 [0 0 9]
 [0 0 0]
 [0 0 0]]


5. turn bt into 1D Array and form a square matrix from it. Make sure the very 1D Array shows up in the band of the matrix.

In [103]:
bt = np.diagflat(bt, k = 0) # k = 0 can be dropped
print(bt)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 6 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 9 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


6. compute the trace of the matrix.

In [104]:
x = np.trace(bt, offset = 0) # offset = 0 can be dropped
print(x)

26
