# Basic Numpy Functions (cont'd)

In [1]:
import numpy as np

# 1. np.hstack / np.vstack

```python
new_mat = np.hstack((a, b, c, ...))
new_mat = np.vstack((a, b, c, ...))
```
* input: tuple of vectors/matrices

## 1.1 2D Array

\begin{align*}
a = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}, \quad
b = \begin{bmatrix}
-1 & -2 \\
-3 & -4
\end{bmatrix}
\end{align*}

$$
\text{np.hstack((a, b))} = \begin{bmatrix}
1 & 2 & 3 & -1 & -2 \\
4 & 5 & 6 & -3 & -4
\end{bmatrix}
$$

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[-1, -2], [-3, -4]])

In [3]:
a.shape

(2, 3)

In [4]:
b.shape

(2, 2)

In [5]:
# a.shape[0] == b.shape[0] : # of rows have to be same for np.hstack
new_mat1 = np.hstack((a, b))
print(new_mat1)

[[ 1  2  3 -1 -2]
 [ 4  5  6 -3 -4]]


\begin{align*}
a = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}, \quad
b = \begin{bmatrix}
-1 & -2 & -3 \\
-4 & -5 & -6 \\
-7 & -8 & -9
\end{bmatrix}
\end{align*}

$$
\text{np.vstack((a, b))} = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
-1 & -2 & -3 \\
-4 & -5 & -6 \\
-7 & -8 & -9 
\end{bmatrix}
$$

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[-1, -2, -3], [-4, -5, -6], [-7, -8, -9]])
print(a.shape)
print(b.shape)

(2, 3)
(3, 3)


In [7]:
# a.shape[1] == b.shape[1] : # of cols have to be same for np.vstack
new_mat2 = np.vstack((a, b))
print(new_mat2)

[[ 1  2  3]
 [ 4  5  6]
 [-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]


## 1.2 1D Array

\begin{align*}
a = \begin{bmatrix}
1  \\
2  \\
3
\end{bmatrix}, \quad
b = \begin{bmatrix}
4  \\
5  \\
6
\end{bmatrix}
\end{align*}

$$
\text{np.hstack((a, b))} = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6 \\
\end{bmatrix}
$$

$$
\text{np.vstack((a, b))} = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 
\end{bmatrix}
$$

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [9]:
new_mat3 = np.hstack((a, b))
print(new_mat3) # 1D Array (concatenated vec)

[1 2 3 4 5 6]


In [10]:
new_mat4 = np.vstack((a, b))
print(new_mat4) # 2D Array 

[[1 2 3]
 [4 5 6]]


## 1.3 2D Array and 1D Array

\begin{align*}
a = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}, \quad
b = \begin{bmatrix}
7  \\
8  \\
9
\end{bmatrix}
\end{align*}

$$
\text{np.vstack((a, b))} = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{bmatrix}
$$

* np.hstack is not defined.

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8, 9])

In [12]:
a.shape[1] == b.size

True

In [13]:
new_mat5 = np.vstack((a, b))
print(new_mat5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 2. Transpose

```python
b = a.transpose()
np.shares_memory(a, b) # True # same memory
```

```python
b = np.copy(a.transpose())
np.shares_memory(a, b) # False # separate memory
```

```python
b = a.T
np.shares_memory(a, b) # True # same memory
```

$$
a = \begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9 
\end{bmatrix}, \quad
b = \begin{bmatrix}
1 & 4 & 7  \\
2 & 5 & 8  \\
3 & 6 & 9
\end{bmatrix}
$$

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
b = a.transpose()
print(b)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [16]:
np.shares_memory(a, b)

True

In [17]:
b2 = np.copy(a.transpose())
print(b2)
np.shares_memory(a, b2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


False

In [18]:
b3 = a.T
print(b3)
np.shares_memory(a, b3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


True

In [19]:
a[0, 0] = -100
print(b)
print(b2)
print(b3)

[[-100    4    7]
 [   2    5    8]
 [   3    6    9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[-100    4    7]
 [   2    5    8]
 [   3    6    9]]


***np.transpose of 1D Array outputs the vector itself.***

In [20]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [21]:
b = a.transpose()
print(b)
print(np.shares_memory(a, b))

[1 2 3]
True


In [22]:
b2 = a.T
print(b)
print(np.shares_memory(a, b))

[1 2 3]
True


# 3. Real property / Imaginary property / Conjugate method

```python
b1 = a.real # real part # ref same memory
```

```python
b2 = a.imag # imag part # return real vec/mat # ref same memory
```

```python
b = a.conjugate() # copy # separate memory 
```

$$
a= \begin{bmatrix}
1 - 2j & 3 + 1j & 1 + 0j \\
1 + 2j & 2 - 1j & 7 + 0j
\end{bmatrix}, \quad
b1 = \begin{bmatrix}
1 & 3 & 1 \\
1 & 2 & 7
\end{bmatrix}, \quad
b2 = \begin{bmatrix}
-2 & 1 & 0 \\
2 & -1 & 0
\end{bmatrix}
$$

$$
a.conjugate() = \begin{bmatrix}
1 + 2j & 3 - 1j & 1 - 0j \\
1 - 2j & 2 + 1j & 7 - 0j
\end{bmatrix}
$$

In [23]:
a = np.array([[1-2j, 3+1j, 1 +0j], [1+2j, 2-1j, 7 +0j]], dtype = np.complex128)
print(a)

[[1.-2.j 3.+1.j 1.+0.j]
 [1.+2.j 2.-1.j 7.+0.j]]


In [24]:
b1 = a.real
print(b1)
print(np.shares_memory(a, b1))

[[1. 3. 1.]
 [1. 2. 7.]]
True


In [25]:
b2 = a.imag
print(b2)
print(np.shares_memory(a, b2))

[[-2.  1.  0.]
 [ 2. -1.  0.]]
True


In [26]:
b = a.conjugate()
print(b)
print(np.shares_memory(a, b))

[[1.+2.j 3.-1.j 1.-0.j]
 [1.-2.j 2.+1.j 7.-0.j]]
False


# 4. Matrix Multiplication

## 4.1 Scalar Multiplication

$$
A = \begin{bmatrix}
1 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 1 
\end{bmatrix}, \quad
r = 5, \quad
rA = \begin{bmatrix}
5 & 10 & 5 \\
10 & 5 & 15 \\
5 & 15 & 5 
\end{bmatrix} 
$$

In [27]:
A = np.array([[1, 2, 1], [2, 1, 3], [1, 3, 1]], dtype = np.float64)
print(a)

[[1.-2.j 3.+1.j 1.+0.j]
 [1.+2.j 2.-1.j 7.+0.j]]


In [28]:
r = 5

In [29]:
result = r*A # A*r

In [30]:
print(result)

[[ 5. 10.  5.]
 [10.  5. 15.]
 [ 5. 15.  5.]]


## 4.2 Matrix Multiplication

$$
A = \begin{bmatrix}
1 & 2 & 1 \\
3 & 2 & 1
\end{bmatrix}, \quad
B = \begin{bmatrix}
2 & 1 \\
1 & 2 \\
-3 & 3
\end{bmatrix}, \quad
AB = \begin{bmatrix}
-5 & 14 \\
5 & 10
\end{bmatrix}
$$

In [31]:
A = np.array([[1, 2, 3], [3, 2, 1]], dtype = np.float64)
B = np.array([[2, 1], [1, 2], [-3, 3]], dtype = np.float64)

In [32]:
result1 = A@B # order matters
print(result1)

[[-5. 14.]
 [ 5. 10.]]


In [33]:
result2 = np.matmul(A, B) # order matters
print(result2)

[[-5. 14.]
 [ 5. 10.]]


## 4.3 Matrix Vector Product

$$
A = \begin{bmatrix}
1 & 2 & 1 \\
2 & 1 & 3 \\
1 & 3 & 1
\end{bmatrix}, \quad
\mathbf{u} = \begin{bmatrix}
5 \\
1 \\
3
\end{bmatrix}, \quad
A\mathbf{u} = \begin{bmatrix}
10 \\
20 \\
11
\end{bmatrix}
$$

In [34]:
A = np.array([[1, 2, 1], [2, 1, 3], [1, 3, 1]], dtype = np.float64)
u = np.array([5, 1, 3])

In [35]:
result1 = A @ u # u is col vec
print(result1)

[10. 20. 11.]


In [36]:
result2 = np.matmul(A, u) # u is col vec
print(result2)

[10. 20. 11.]


```python
np.dot
```
* not recommended for matrix vector product. because of its name, it can be confusing.

## 4.4 Inner Product

```python
result = np.vdot(u, v)
```

**Definition**
\begin{align*}
\textbf{real vector:} & \quad \mathbf{u} \cdot \mathbf{v} = u_1 v_1 + u_2 v_2 + \cdots + u_n v_n \\[8pt]
\textbf{complex vector:} & \quad \mathbf{u} \cdot \mathbf{v} = u_1 \overline{v_1} + u_2 \overline{v_2} + \cdots + u_n \overline{v_n}
\end{align*}

However, when it comes to inner product of complex vectors, **numpy** returns following value:

\begin{align*}
\textbf{complex vector:} & \quad \mathbf{u} \cdot \mathbf{v} = \overline{u_1} v_1 + \overline{u_2} v_2 + \cdots + \overline{u_n} v_n
\end{align*}

In [37]:
a = np.array([1-2j, 3+1j, 1 +0j], dtype = np.complex128)
b = np.array([1+2j, 2-1j, 7 +0j], dtype = np.complex128)
result = np.vdot(a, b)
print(result)

(9-1j)


```python
result = np.dot(u, v)
```
* for real vectors, returns same results as np.vdot
* for complex vectors, returns with out taking conjugates; just like real vectors (***this is not inner product**)

## 4.5 Norm

\begin{aligned}
\text{$\ell_1$-vector norm:} & \quad \|\mathbf{x}\|_1 = \sum_{i=1}^n |x_i| \\[8pt]
\text{$\ell_2$-vector norm (Euclidean):} & \quad \|\mathbf{x}\|_2 = \left( \sum_{i=1}^n x_i^2 \right)^{1/2} \\[8pt]
\text{$\ell_\infty$-vector norm:} & \quad \|\mathbf{x}\|_\infty = \max_{1 \leq i \leq n} |x_i| \\[16pt]
\text{$\ell_1$-matrix norm:} & \quad \|\mathbf{A}\|_1 = \max_{1 \leq j \leq n} \sum_{i=1}^m |a_{ij}| \\[8pt]
\text{$\ell_2$-matrix norm (spectral):} & \quad \|\mathbf{A}\|_2 = \sigma_{\max} \leq \left( \sum_{i=1}^m \sum_{j=1}^n |a_{ij}|^2 \right)^{1/2} \\[8pt]
\text{$\ell_\infty$-matrix norm:} & \quad \|\mathbf{A}\|_\infty = \max_{1 \leq i \leq m} \sum_{j=1}^n |a_{ij}|
\end{aligned}

In [38]:
from scipy import linalg

```python
norm = linalg.norm(a, 1)
norm = linalg.norm(a, 2) # a is either a vector or matrix # l2 norm # for l_inf, use inf # default = 2
norm = linalg.norm(a, inf)
```

# 5. Extracting a Part from a Matrix / Vector

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & \cellcolor{black!20}{7} & \cellcolor{black!20}{8} & \cellcolor{black!20}{9} & 10 \\
11 & \cellcolor{black!20}{12} & \cellcolor{black!20}{13} & \cellcolor{black!20}{14} & 15 \\
-1 & -2 & -3 & -4 & -5
\end{bmatrix}
$$

In [39]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [-1, -2, -3, -4, -5]
], dtype=np.int64)

**Case 1.**

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & \cellcolor{black!20}{7} & \cellcolor{black!20}{8} & \cellcolor{black!20}{9} & 10 \\
11 & \cellcolor{black!20}{12} & \cellcolor{black!20}{13} & \cellcolor{black!20}{14} & 15 \\
-1 & -2 & -3 & -4 & -5
\end{bmatrix}, \quad \\
A' =
\begin{bmatrix}
\cellcolor{black!20}{7} & \cellcolor{black!20}{8} & \cellcolor{black!20}{9}\\
\cellcolor{black!20}{12} & \cellcolor{black!20}{13} & \cellcolor{black!20}{14}
\end{bmatrix}
$$

In [40]:
sub_A = A[1:3, 1:4] # slicing
print(sub_A)

[[ 7  8  9]
 [12 13 14]]


In [41]:
# ref same memory
np.shares_memory(A, sub_A)

True

**Case 2.**

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & \cellcolor{black!20}{7} & \cellcolor{black!20}{8} & \cellcolor{black!20}{9} & 10 \\
11 & \cellcolor{black!20}{12} & \cellcolor{black!20}{13} & \cellcolor{black!20}{14} & 15 \\
-1 & -2 & -3 & -4 & -5
\end{bmatrix}, \quad \\
A' =
\begin{bmatrix}
3 & 4 & 5 \\
\cellcolor{black!20}{8} & \cellcolor{black!20}{9} & 10 \\
\cellcolor{black!20}{13} & \cellcolor{black!20}{14} & 15 \\
-3 & -4 & -5
\end{bmatrix}
$$

In [42]:
sub_A = A[0:4, 2:6]
print(sub_A)
print(np.shares_memory(A, sub_A))

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [-3 -4 -5]]
True


In [43]:
sub_A = A[:, 2:]
print(sub_A)
print(np.shares_memory(A, sub_A))

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [-3 -4 -5]]
True


**Case 3.1**

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & \cellcolor{black!20}{7} & \cellcolor{black!20}{8} & \cellcolor{black!20}{9} & 10 \\
11 & \cellcolor{black!20}{12} & \cellcolor{black!20}{13} & \cellcolor{black!20}{14} & 15 \\
-1 & -2 & -3 & -4 & -5
\end{bmatrix}, \quad \\
A' =
\begin{bmatrix}
7 & 8 & 9
\end{bmatrix}
$$

In [44]:
sub_A = A[1:2, 1:4]
print(sub_A) # 2D Array
print(np.shares_memory(A, sub_A))
print(sub_A.shape)

[[7 8 9]]
True
(1, 3)


In [45]:
sub_A = A[1, 1:4]
print(sub_A) # 1D Array
print(np.shares_memory(A, sub_A))
print(sub_A.shape)

[7 8 9]
True
(3,)


In [46]:
print(np.reshape(sub_A, (1, 3)))
print(np.reshape(sub_A, (1, -1))) # 3 is computed automatically

[[7 8 9]]
[[7 8 9]]


**Case 3.2**

$$
A =
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & \cellcolor{black!20}{7} & \cellcolor{black!20}{8} & \cellcolor{black!20}{9} & 10 \\
11 & \cellcolor{black!20}{12} & \cellcolor{black!20}{13} & \cellcolor{black!20}{14} & 15 \\
-1 & -2 & -3 & -4 & -5
\end{bmatrix}, \quad \\
A' =
\begin{bmatrix}
7\\
12\\
-2
\end{bmatrix}
$$

In [47]:
sub_A = A[1:4, 1:2]
print(sub_A) # 2D Array
print(np.shares_memory(A, sub_A))
print(sub_A.shape)

[[ 7]
 [12]
 [-2]]
True
(3, 1)


In [48]:
sub_A = A[1:4, 1]
print(sub_A) # 1D Array
print(np.shares_memory(A, sub_A))
print(sub_A.shape)

[ 7 12 -2]
True
(3,)


In [49]:
print(np.reshape(sub_A, (3, 1)))
print(np.reshape(sub_A, (3, -1))) # 1 is computed automatically

[[ 7]
 [12]
 [-2]]
[[ 7]
 [12]
 [-2]]


## Practice 1.

$$
A = \begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
-1 & -2 & -3 & -4 & -5
\end{bmatrix}, \quad
B = \begin{bmatrix}
2 & 7 & 12 & -2 \\
3 & 8 & 13 & -3 \\
4 & 9 & 14 & -4
\end{bmatrix}
$$

1. Store matrix $A$ as a 2D Array in variable A
2. Save the 2nd, 3rd, 4th column vectors of $A$ as $v_1$, $v_2$, $v_3$
3. Use $v_1$, $v_2$, $v_3$ to form $B$
4. Compute a matrix vector product of $B$ and $v_1$

1. Store matrix $A$ as a 2D Array in variable A

In [50]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [-1, -2, -3, -4, -5]
])

2. Save the 2nd, 3rd, 4th column vectors of $A$ as $v_1$, $v_2$, $v_3$


In [51]:
v1 = A[:, 1] # 1D Array, hereafter
v2 = A[:, 2]
v3 = A[:, 3]

3. Use $v_1$, $v_2$, $v_3$ to form $B$

In [52]:
B = np.vstack((v1, v2, v3))
print(B)

[[ 2  7 12 -2]
 [ 3  8 13 -3]
 [ 4  9 14 -4]]


4. Compute a matrix vector product of $B$ and $v_1$

In [53]:
if B.shape[1] == v1.size:  # should be true
    result = np.matmul(B, v1) # B @ v1
    print(result)

[201 224 247]


## Practice 2.

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}, \quad
\mathbf{x} = \begin{bmatrix}
5 \\
6
\end{bmatrix}
$$

1. Store $A$ and $\mathbf{x}$ as 2D and 1D Arrays respectively as A and x
2. Check whether *np.transpose* works for the 1D Array
3. Calculate the quadratic form, $\mathbf{x}^\top A\mathbf{x}$
   * $\mathbf{x}^\top$: use *np.reshape* instead
   * use *np.vdot* to compute the quadratic form

1. Store $A$ and $\mathbf{x}$ as 2D and 1D Arrays respectively as A and x

In [54]:
A = np.array([
    [1, 2],
    [3, 4]
])
x = np.array([5, 6])
print(A)
print(x)

[[1 2]
 [3 4]]
[5 6]


2. Check whether *np.transpose* works for the 1D Array

In [55]:
print(x.T)

[5 6]


3. Calculate the quadratic form, $\mathbf{x}^\top A\mathbf{x}$
   * $\mathbf{x}^\top$: use *np.reshape* instead
   * use *np.vdot* to compute the quadratic form

In [56]:
# transpose of vector, x
x_t = np.reshape(x, (2, 1))

In [57]:
# quadratic form
np.vdot(x_t, A @ x)

np.int64(319)